### ISSUE TITLE
Error when not using the data_path flag

### ISSUE THREAD

**Issue by ManuelOHarke** [Biomathsys/MassChargeCuration#2]
When there is already a folder named _./data_, that doesn't contain database information, and the flag `data_path` isn't set in

`balancer = MassChargeCuration(model = model, run_optimization = True, update_ids = True)`

The following error will appear:

`File not found Error: ./data/chem_xref.tsv`

This can be resolved by setting the `data_path` flag to a subfolder. Is the `data_path` flag mandatory?

**Comment by Finnem** [comment]
This issue is resolved by commit [e3b8909](https://github.com/Biomathsys/MassChargeCuration/commit/a617d0d82ce060b9464e7a27213b8ff3d9d6a0af).
