### ISSUE TITLE
Misleading ReadMe

### ISSUE THREAD

**Issue by famosab** [Biomathsys/MassChargeCuration#4]
When first loading my model with cobrapy as described in the readme

`model = cobra.io.read_sbml_model(model_path)`

and then using MCC as described

`balancer = MassChargeCuration(model, update_ids = True)`

I run into `GurobiError: Unable to read model`.

After having a look into the Example I found that I could directly feed the `model_path` into MCC and then it worked.
`balancer = MassChargeCuration(model_path, update_ids = True)`

**Comment by GwennyGit** [comment]
As @famosab already stated there is a problem when using a previously loaded model as input for the MassChargeCuration. However, my error message stated that `reaction.sbo` should be an `int`, `str` or number and not a `list`.
After I solved this issue by using the Path to the model directly as input I realised that the call to MassChargeCuration as described in the README does not work. In the README it says: `balancer = MassChargeCuration(model, update_ids = True)` which does not work as then the `data_path` does not exist. At least it did not work for me until I added `data_path='./data'` This should also be added to the README. I only found a fix for that issue by looking at the example jupyter notebook.

**Comment by Finnem** [comment]
This issue is resolved by commit [a617d0d](https://github.com/Biomathsys/MassChargeCuration/commit/a617d0d82ce060b9464e7a27213b8ff3d9d6a0af) and [0c2ef8f](https://github.com/Biomathsys/MassChargeCuration/commit/0c2ef8feb15ad7f54295513f0fc274ff7d6f66aa).
