### ISSUE TITLE
Progress is not visible to user

### ISSUE THREAD

**Issue by famosab** [Biomathsys/MassChargeCuration#5]
It would be helpful to have a progress bar that shows where the program is at timewise. The way its implemented now, I have no idea whether it is still running as it should and just takes its time or whether something went wrong.

A very easy way to implement that into python code is using the package `tqdm`. I did that (as mentioned in [this](https://github.com/draeger-lab/refinegems/issues/10) issue) in [refinegems/polish_carveme.py](https://github.com/draeger-lab/refinegems/blob/main/refinegems/polish_carveme.py).

**Comment by Finnem** [comment]
This issue is resolved by commit [092578e](https://github.com/Biomathsys/MassChargeCuration/commit/092578e0f9edba896a47189175997299fb4289a2).
